name: bcproxyai
services:
  bcproxyai:
    image: bcproxyai
    build: .
    ports:
      - "3334:3000"
    env_file:
      - .env.local
    volumes:
      - bcproxyai-data:/app/data
volumes:
  bcproxyai-data:
